export {default as MainPage } from "./MainPage"
export {default as ErrorPage } from "./ErrorPage"
export {default as PeoplePage } from "./PeoplePage"
export {default as PlanetPage } from "./PlanetPage"
export {default as StarshipsPage } from "./StarshipsPage"
export {default as PeopleInfo } from "./routerInfo/PeopleInfo"
export {default as PlanetsInfo } from "./routerInfo/PlanetsInfo"
export {default as StarshipsInfo } from "./routerInfo/StarshipsInfo"